name: Use Action

on:
  pull_request_target:
    branches:
      - 'main'

permissions: {}

jobs:
  use-action:
    name: Use Action
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed to federate with octo-sts

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          persist-credentials: false

      - id: octo-sts
        uses: ./
        with:
          scope: octo-sts/action
          identity: use-action

      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: gh repo list | grep octo-sts
